server.port=${PORT:8080}
logging.level.org.atmosphere=warn

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=true

# To improve the performance during development.
# For more information https://vaadin.com/docs/latest/flow/integrations/spring/configuration#special-configuration-parameters
vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,com.clima

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://martinvozmeudla:Martokun32@cluster0.ihk5zwd.mongodb.net/sistema_clima?appName=Cluster0
# spring.data.mongodb.database=sistema_clima